import type { Scenario } from "./types";

export const ukraineScenario: Scenario = {
  id: "ukraine-signal",
  name: "The Ukraine Signal",
  description: "GDELT burst detects cease-fire talks resuming, triggering full CHIMERA pipeline",
  durationMs: 180000,
  graph: {
    nodes: [
      { id: "Ukraine", type: "country" },
      { id: "Russia", type: "country" },
      { id: "Ceasefire", type: "concept" },
      { id: "Sanctions", type: "concept" },
      { id: "Oil Prices", type: "concept" },
      { id: "NATO", type: "organization" },
      { id: "EU", type: "organization" },
      { id: "Putin", type: "person" },
      { id: "Zelensky", type: "person" },
      { id: "Recession", type: "concept" },
      { id: "S&P 500", type: "concept" },
      { id: "Bitcoin", type: "concept" },
      { id: "Interest Rates", type: "concept" },
      { id: "Inflation", type: "concept" },
    ],
    edges: [
      { source: "Ukraine", target: "Ceasefire", relation: "negotiates", weight: 0.8 },
      { source: "Russia", target: "Ceasefire", relation: "considers", weight: 0.6 },
      { source: "Ceasefire", target: "Sanctions", relation: "may_reduce", weight: 0.7 },
      { source: "Sanctions", target: "Oil Prices", relation: "increases", weight: 0.7 },
      { source: "Sanctions", target: "Russia", relation: "pressures", weight: 0.8 },
      { source: "Oil Prices", target: "Inflation", relation: "drives", weight: 0.6 },
      { source: "Inflation", target: "Interest Rates", relation: "pressures_up", weight: 0.7 },
      { source: "Interest Rates", target: "S&P 500", relation: "inversely_affects", weight: 0.6 },
      { source: "Interest Rates", target: "Bitcoin", relation: "inversely_affects", weight: 0.5 },
      { source: "NATO", target: "Ukraine", relation: "supports", weight: 0.8 },
      { source: "Recession", target: "S&P 500", relation: "crashes", weight: 0.8 },
      { source: "Oil Prices", target: "Recession", relation: "risk_of", weight: 0.4 },
    ],
  },
  signals: [
    {
      id: "sig-1", source: "oracle", signal_type: "news_cluster", score: 0.87,
      title: "Reuters: Ukraine cease-fire talks to resume in Istanbul",
      detail: "47 articles in 12 minutes (3.8x baseline). Sources: Reuters, AP, BBC, Al Jazeera, Ukrinform",
      timestamp: new Date().toISOString(), data: { velocity: 3.92, source_diversity: 5 },
      offsetMs: 3000,
    },
    {
      id: "sig-2", source: "oracle", signal_type: "wikipedia_spike", score: 0.72,
      title: 'Wikipedia spike: "Minsk Protocol" edits +280%',
      detail: "Pageviews 4.2x baseline (340/hr vs 81/hr normal)",
      timestamp: new Date().toISOString(), data: { spike_ratio: 4.2 },
      offsetMs: 8000,
    },
    {
      id: "sig-3", source: "predator", signal_type: "vpin_spike", score: 0.73,
      title: "VPIN spike: 0.73 on Ukraine conflict market",
      detail: "Informed flow detected — VPIN exceeded 0.60 threshold",
      timestamp: new Date().toISOString(), data: { vpin: 0.73 },
      offsetMs: 15000,
    },
    {
      id: "sig-4", source: "predator", signal_type: "whale_move", score: 0.68,
      title: "Whale alert: 3 wallets bought $45K YES in 8 minutes",
      detail: "Top wallets 0x7a3f...8b2c, 0x4e2d...1a9f, 0xbc45...3d7e all buying",
      timestamp: new Date().toISOString(), data: { whale_count: 3, total: 45000 },
      offsetMs: 20000,
    },
  ],
  waterfall: [
    { id: "w1", timestamp: new Date().toISOString(), phase: "ORACLE", title: "Scanning data sources...", detail: "RSS, GDELT, Wikipedia, Cloudflare Radar", offsetMs: 1000 },
    { id: "w2", timestamp: new Date().toISOString(), phase: "ORACLE", title: "GDELT burst: Ukraine cease-fire talks", detail: "47 articles, 3.8x velocity, 5 independent sources", probability: 0.31, offsetMs: 5000 },
    { id: "w3", timestamp: new Date().toISOString(), phase: "ORACLE", title: 'Wikipedia spike: "Minsk Protocol"', detail: "Edits +280%, pageviews 4.2x baseline", offsetMs: 10000 },
    { id: "w4", timestamp: new Date().toISOString(), phase: "PREDATOR", title: "VPIN: 0.73 | Imbalance: +0.34", detail: "Informed flow detected. Spread: 0.023, Liquidity: 0.71", probability: 0.31, offsetMs: 18000 },
    { id: "w5", timestamp: new Date().toISOString(), phase: "PREDATOR", title: "Whale alert: 3 wallets, $45K buy-side", detail: "Whale consensus: BUY (100% aligned)", offsetMs: 22000 },
    { id: "w6", timestamp: new Date().toISOString(), phase: "RIPPLE", title: "4 second-order effects detected", detail: "Ceasefire → Sanctions relief → Oil prices → Inflation cascade", offsetMs: 30000 },
    { id: "w7", timestamp: new Date().toISOString(), phase: "HYDRA", title: "Multi-agent debate starting...", detail: "Bull, Bear, Historian, Contrarian, Quant → Judge", offsetMs: 35000 },
    { id: "w8", timestamp: new Date().toISOString(), phase: "HYDRA", title: "Round 1: Bull 68% | Bear 41% | Historian 55% | Contrarian 38% | Quant 62%", detail: "Divergence detected — Contrarian flags cascade risk", probability: 0.53, offsetMs: 55000 },
    { id: "w9", timestamp: new Date().toISOString(), phase: "HYDRA", title: "Contrarian challenge: 'Ceasefire talks have collapsed 4 times before'", detail: "Agents revising... Bull→65%, Bear→44%, Historian stable, Quant→59%", offsetMs: 70000 },
    { id: "w10", timestamp: new Date().toISOString(), phase: "HYDRA", title: "Judge synthesis → 58% (confidence: 0.72)", detail: "Weighted by evidence quality and stability. Dissent: 'Prior talks all failed within 2 weeks'", probability: 0.58, confidence: 0.72, offsetMs: 85000 },
    { id: "w11", timestamp: new Date().toISOString(), phase: "FUSION", title: "Signal fusion: 58% → extremized → 63%", detail: "Log-odds aggregation + RIPPLE adj (+0.04) + GJP extremize (d=1.5). Market: 31%", probability: 0.63, offsetMs: 95000 },
    { id: "w12", timestamp: new Date().toISOString(), phase: "FUSION", title: "Edge: +32% → Kelly: 11.6% → $116.00", detail: "Fractional Kelly (25%), bankroll cap (5%). Risk checks: ALL PASSED", probability: 0.63, confidence: 0.72, offsetMs: 100000 },
    { id: "w13", timestamp: new Date().toISOString(), phase: "EXECUTE", title: "BUY YES $116.00 @ 0.31", detail: "Limit order placed. Status: FILLED", probability: 0.63, offsetMs: 110000 },
  ],
  debates: [
    {
      market_id: "ukraine-conflict-end",
      market_question: "Will there be a Ukraine cease-fire agreement by July 2026?",
      rounds: [
        {
          round_number: 1,
          challenge_text: "",
          votes: [
            { agent_name: "Bull", agent_role: "bull", probability: 0.68, confidence: 0.7, reasoning: "Multiple credible sources confirm talks resuming. Turkey facilitating. Both sides showing economic exhaustion. Recent prisoner exchanges signal goodwill.", key_evidence: ["Reuters confirms Istanbul venue", "Both economies showing strain", "Prisoner exchanges accelerating"], round_number: 1 },
            { agent_name: "Bear", agent_role: "bear", probability: 0.41, confidence: 0.65, reasoning: "Cease-fire talks have resumed and collapsed 4 times since 2022. Territorial disputes remain unresolved. Neither side has made territorial concessions.", key_evidence: ["4 prior failed negotiations", "No territorial concessions", "Battlefield momentum unclear"], round_number: 1 },
            { agent_name: "Historian", agent_role: "historian", probability: 0.55, confidence: 0.8, reasoning: "Base rate: of 47 similar armed conflicts since 1946, 34% achieved ceasefire within 4 years. Ukraine conflict at ~4 years. Adjusting up slightly for economic pressure on both sides.", key_evidence: ["Base rate: 34% for 4+ year conflicts", "Economic exhaustion parallel to Korean War 1953", "International mediation increases odds by ~15%"], round_number: 1 },
            { agent_name: "Contrarian", agent_role: "contrarian", probability: 0.38, confidence: 0.6, reasoning: "The market is underpricing failure risk. Information cascade — all agents anchoring on the same Reuters report. No independent verification of Russian willingness. Domestic politics in both countries make concessions electorally toxic.", key_evidence: ["Single-source anchoring risk", "Domestic political constraints", "Russia has walked out before"], round_number: 1 },
            { agent_name: "Quant", agent_role: "quant", probability: 0.62, confidence: 0.75, reasoning: "VPIN at 0.73 indicates informed buying. 3 whale wallets accumulated $45K in 8 minutes. Order book imbalance: +0.34 (bullish). Cross-market: Ruble strengthened 1.2% in parallel.", key_evidence: ["VPIN 0.73 > threshold 0.60", "3 whale wallets aligned", "Ruble +1.2% correlated"], round_number: 1 },
          ],
        },
        {
          round_number: 2,
          challenge_text: "Cease-fire talks have collapsed 4 times before. The group is anchoring on a single Reuters report. No independent verification of Russian willingness exists. Markets moved before on similar rumors and reverted within 48 hours.",
          votes: [
            { agent_name: "Bull", agent_role: "bull", probability: 0.65, confidence: 0.65, reasoning: "Revised down 3pp. Acknowledging prior failures but noting this round has novel element: Turkish mediation and economic pressure not present in 2022-2023 rounds.", key_evidence: ["Revised from 68% to 65%", "Turkish mediation is new", "Economic pressure stronger now"], round_number: 2 },
            { agent_name: "Bear", agent_role: "bear", probability: 0.44, confidence: 0.7, reasoning: "Increased slightly. The whale activity and VPIN data do suggest informed buying, which I can't fully dismiss. But maintaining that structural barriers dominate.", key_evidence: ["Whale data is notable", "Structural barriers remain", "Revised from 41% to 44%"], round_number: 2 },
            { agent_name: "Historian", agent_role: "historian", probability: 0.55, confidence: 0.82, reasoning: "Maintaining position. Base rate analysis is independent of news cycle. The Contrarian's challenge reinforces the outside view — narrative-driven agents shifted, I didn't.", key_evidence: ["Base rate unchanged", "Outside view stable", "High confidence in methodology"], round_number: 2 },
            { agent_name: "Contrarian", agent_role: "contrarian", probability: 0.38, confidence: 0.6, reasoning: "Maintaining. The group's partial convergence after my challenge is itself evidence of cascade dynamics. True independent information would produce more divergence.", key_evidence: ["Convergence = cascade signal", "Maintaining contrarian position"], round_number: 2 },
            { agent_name: "Quant", agent_role: "quant", probability: 0.59, confidence: 0.7, reasoning: "Revised down 3pp. Contrarian raised valid point about single-source risk. However, the on-chain data is multi-source and independent. VPIN doesn't lie.", key_evidence: ["On-chain data is independent", "VPIN is multi-source", "Revised from 62% to 59%"], round_number: 2 },
          ],
        },
      ],
      judge_probability: 0.58,
      judge_confidence: 0.72,
      judge_reasoning: "Weighting Historian (stable, methodology-grounded) and Quant (independent on-chain evidence) most heavily. Bull and Bear both shifted toward center, showing healthy uncertainty. Contrarian's cascade warning is noted but the VPIN and whale data provide independent confirmation beyond the Reuters report. Final: 58%.",
      dissenting_view: "Prior cease-fire talks have collapsed 4 times. The market may be right at 31% — we could be overweighting a single news cycle that reverts within 48 hours.",
      offsetMs: 45000,
    },
  ],
  trades: [
    {
      market_id: "ukraine-conflict-end",
      market_question: "Will there be a Ukraine cease-fire agreement by July 2026?",
      direction: "YES",
      estimated_probability: 0.63,
      market_price: 0.31,
      edge: 0.32,
      kelly_fraction: 0.116,
      bet_amount: 116.0,
      confidence: 0.72,
      rationale: "Fused 3 signals. Raw: 0.565 → Adjusted: 0.585 → Extremized: 0.630. Edge: 32.0% (YES). Kelly: 11.6% of bankroll = $116.00",
      timestamp: new Date().toISOString(),
      offsetMs: 110000,
    },
  ],
  rippleEvents: [
    { offsetMs: 30000, sourceNodeId: "Ceasefire" },
    { offsetMs: 33000, sourceNodeId: "Sanctions" },
    { offsetMs: 36000, sourceNodeId: "Oil Prices" },
  ],
};

export const tariffShockScenario: Scenario = {
  id: "tariff-shock",
  name: "The Tariff Shock",
  description: "USTR gov site change detected — new 45% China tariff before any news breaks",
  durationMs: 120000,
  graph: {
    nodes: [
      { id: "Trump", type: "person" },
      { id: "China", type: "country" },
      { id: "USA", type: "country" },
      { id: "Tariffs", type: "concept" },
      { id: "Trade War", type: "concept" },
      { id: "Supply Chain", type: "concept" },
      { id: "Inflation", type: "concept" },
      { id: "S&P 500", type: "concept" },
      { id: "Recession", type: "concept" },
      { id: "Fed", type: "organization" },
      { id: "Interest Rates", type: "concept" },
      { id: "Bitcoin", type: "concept" },
      { id: "Yuan", type: "concept" },
    ],
    edges: [
      { source: "Trump", target: "Tariffs", relation: "announces", weight: 0.95 },
      { source: "Tariffs", target: "China", relation: "targets", weight: 0.9 },
      { source: "Tariffs", target: "Trade War", relation: "escalates_to", weight: 0.8 },
      { source: "Trade War", target: "Supply Chain", relation: "disrupts", weight: 0.75 },
      { source: "Supply Chain", target: "Inflation", relation: "drives", weight: 0.7 },
      { source: "Inflation", target: "Fed", relation: "pressures", weight: 0.6 },
      { source: "Fed", target: "Interest Rates", relation: "raises", weight: 0.65 },
      { source: "Interest Rates", target: "S&P 500", relation: "inversely_affects", weight: 0.7 },
      { source: "Trade War", target: "S&P 500", relation: "crashes", weight: 0.8 },
      { source: "S&P 500", target: "Recession", relation: "signals", weight: 0.6 },
      { source: "China", target: "Yuan", relation: "devalues", weight: 0.7 },
      { source: "Recession", target: "Bitcoin", relation: "risk_off", weight: 0.5 },
    ],
  },
  signals: [
    {
      id: "sig-t1", source: "oracle", signal_type: "gov_change", score: 0.91,
      title: "USTR.gov change: 45% tariff schedule added to China import page",
      detail: "Page diff detected 23 minutes before White House briefing. 847 words added to trade enforcement section.",
      timestamp: new Date().toISOString(), data: { page: "ustr.gov/tariff-schedule", words_added: 847 },
      offsetMs: 2000,
    },
    {
      id: "sig-t2", source: "predator", signal_type: "cascade", score: 0.84,
      title: "Cascade detected: S&P 500 recession market one-sided sell flow",
      detail: "15 consecutive sell trades. Directional ratio: 0.93. Cascade score: 0.87",
      timestamp: new Date().toISOString(), data: { cascade_score: 0.87, directional_ratio: 0.93 },
      offsetMs: 9000,
    },
    {
      id: "sig-t3", source: "oracle", signal_type: "news_cluster", score: 0.88,
      title: "Reuters/Bloomberg: White House confirms 45% China tariffs effective Monday",
      detail: "34 articles in 6 minutes. Velocity: 5.7x baseline. Market moved before this broke.",
      timestamp: new Date().toISOString(), data: { velocity: 5.7, articles: 34 },
      offsetMs: 18000,
    },
    {
      id: "sig-t4", source: "predator", signal_type: "vpin_spike", score: 0.79,
      title: "VPIN: 0.81 on US recession market",
      detail: "Highest informed flow reading in 48 hours. Threshold: 0.60",
      timestamp: new Date().toISOString(), data: { vpin: 0.81 },
      offsetMs: 24000,
    },
  ],
  waterfall: [
    { id: "tw1", timestamp: new Date().toISOString(), phase: "ORACLE", title: "Gov website monitor: USTR.gov diff detected", detail: "847 words inserted into tariff-schedule/china section at 09:34 UTC", offsetMs: 1000 },
    { id: "tw2", timestamp: new Date().toISOString(), phase: "ORACLE", title: "Tariff schedule: 45% on $380B Chinese goods", detail: "Page change precedes White House briefing by 23 minutes. High-confidence signal.", probability: 0.22, offsetMs: 4000 },
    { id: "tw3", timestamp: new Date().toISOString(), phase: "PREDATOR", title: "Cascade score: 0.87 | VPIN: 0.81", detail: "Information cascade triggered. 15 consecutive sell trades on recession market.", probability: 0.22, offsetMs: 12000 },
    { id: "tw4", timestamp: new Date().toISOString(), phase: "PREDATOR", title: "Order book: spread +0.041, depth collapse on NO side", detail: "Liquidity draining from YES side. Market makers stepping back.", offsetMs: 20000 },
    { id: "tw5", timestamp: new Date().toISOString(), phase: "RIPPLE", title: "5 second-order effects propagated", detail: "Tariffs → Trade War → Supply Chain → Inflation → S&P crash → Recession cascade", offsetMs: 26000 },
    { id: "tw6", timestamp: new Date().toISOString(), phase: "RIPPLE", title: "RIPPLE adjustment: +0.08 toward YES (recession)", detail: "3 causal hops, weighted decay 0.6^depth. Strong causal chain.", offsetMs: 30000 },
    { id: "tw7", timestamp: new Date().toISOString(), phase: "HYDRA", title: "Debate initiated: Will US GDP contract in H2 2026?", detail: "Market at 22%. CHIMERA entering debate with strong prior signal.", offsetMs: 33000 },
    { id: "tw8", timestamp: new Date().toISOString(), phase: "HYDRA", title: "Round 1: Bull 31% | Bear 64% | Historian 52% | Contrarian 28% | Quant 69%", detail: "Strong bearish consensus. Contrarian pushing back hard.", probability: 0.49, offsetMs: 48000 },
    { id: "tw9", timestamp: new Date().toISOString(), phase: "HYDRA", title: "Contrarian: 'Tariffs often walk back. Trump negotiates with tariff threats'", detail: "Historical note: USMCA, Phase 1 China deal both started with maximalist tariff threats.", offsetMs: 60000 },
    { id: "tw10", timestamp: new Date().toISOString(), phase: "HYDRA", title: "Judge synthesis → 55% recession probability (confidence: 0.78)", detail: "Bear/Quant weighted heavily. Contrarian dissent noted but USTR page diff is harder evidence than rhetoric.", probability: 0.55, confidence: 0.78, offsetMs: 72000 },
    { id: "tw11", timestamp: new Date().toISOString(), phase: "FUSION", title: "Fusion: 55% → RIPPLE +0.08 → 59% → extremized → 65%", detail: "d=1.5 GJP extremize. Market: 22%. Edge: +43%", probability: 0.65, offsetMs: 82000 },
    { id: "tw12", timestamp: new Date().toISOString(), phase: "FUSION", title: "Kelly: 24.5% → capped 5% → $50.00 (conservative)", detail: "Large edge triggers max-bet cap. Risk management engaged.", probability: 0.65, confidence: 0.78, offsetMs: 88000 },
    { id: "tw13", timestamp: new Date().toISOString(), phase: "EXECUTE", title: "BUY YES $50.00 @ 0.22 — FILLED", detail: "Limit order. Expected value: +$127.27 if correct. Max loss: $50.00", probability: 0.65, offsetMs: 96000 },
  ],
  debates: [
    {
      market_id: "us-recession-2026",
      market_question: "Will US GDP contract for 2+ consecutive quarters in H2 2026?",
      rounds: [
        {
          round_number: 1,
          challenge_text: "",
          votes: [
            { agent_name: "Bull", agent_role: "bull", probability: 0.31, confidence: 0.6, reasoning: "US economy has proven resilient. Labor market remains strong at 3.8% unemployment. Consumer spending has held through prior tariff rounds. Fed has rate-cut room if needed.", key_evidence: ["Labor market: 3.8% unemployment", "Consumer spending still positive", "Fed has 200bps cutting room"], round_number: 1 },
            { agent_name: "Bear", agent_role: "bear", probability: 0.64, confidence: 0.75, reasoning: "45% tariffs on $380B goods is unprecedented since Smoot-Hawley. Supply chain disruption will take 6-12 months to propagate fully into CPI. Retaliatory tariffs from China will hit agricultural sector hard. CEO surveys already showing capex freeze.", key_evidence: ["45% tariff unprecedented in modern era", "China retaliation certain (historical pattern)", "CEO capex freeze surveys", "Supply chain lag 6-12 months"], round_number: 1 },
            { agent_name: "Historian", agent_role: "historian", probability: 0.52, confidence: 0.7, reasoning: "Base rate for tariff-induced recessions: 3 of 7 major tariff escalations since 1930 led to recession within 18 months (43%). Adjusting up for magnitude and speed of this escalation. Smoot-Hawley parallel is imperfect but instructive.", key_evidence: ["Base rate 43% for major tariff escalations", "Smoot-Hawley: -26% GDP over 3 years (different era)", "NAFTA reversal parallel: -0.4% GDP impact"], round_number: 1 },
            { agent_name: "Contrarian", agent_role: "contrarian", probability: 0.28, confidence: 0.65, reasoning: "This market is showing classic narrative cascade. Trump has used 45% tariff threats as negotiating leverage 3 times (Canada 2025, EU 2025, Mexico 2025) — all walked back within 60 days. The USTR page change could be a negotiating position, not enacted policy.", key_evidence: ["3 prior tariff threats walked back in 2025", "USTR changes have been reversed before", "Phase 1 China deal started at 25% tariffs"], round_number: 1 },
            { agent_name: "Quant", agent_role: "quant", probability: 0.69, confidence: 0.8, reasoning: "Hard data: VPIN 0.81 (highest in 48h), cascade score 0.87, order book depth collapse on YES side. Gov page changes are harder signals than rhetoric — they require actual regulatory work to publish. Cross-market: Yuan futures pricing in 3.2% devaluation.", key_evidence: ["VPIN 0.81 — informed flow", "Gov page change = harder than tweet", "Yuan futures: 3.2% devaluation priced", "Cascade: 15 consecutive sell trades"], round_number: 1 },
          ],
        },
        {
          round_number: 2,
          challenge_text: "Trump has used 45% tariff threats as negotiating leverage three separate times in 2025 alone — Canada, EU, Mexico — and walked all three back within 60 days. The USTR page change could be a regulatory placeholder for a negotiating position, not enacted policy. We may be overreacting to a page edit.",
          votes: [
            { agent_name: "Bull", agent_role: "bull", probability: 0.31, confidence: 0.62, reasoning: "Maintaining. Contrarian's point aligns with my view. The three 2025 precedents are directly comparable. Resilient labor market means even if tariffs stick, recession is not guaranteed.", key_evidence: ["3 precedents of walkback", "Labor market buffer", "Maintaining 31%"], round_number: 2 },
            { agent_name: "Bear", agent_role: "bear", probability: 0.61, confidence: 0.72, reasoning: "Revised down 3pp, acknowledging the walkback precedents. But: China is different. Canada/EU/Mexico are allies — China is a strategic adversary. The political incentives to maintain China tariffs are much stronger domestically.", key_evidence: ["China is strategic adversary — different dynamic", "Domestic politics favor China hardline", "Revised 64%→61%"], round_number: 2 },
            { agent_name: "Historian", agent_role: "historian", probability: 0.48, confidence: 0.68, reasoning: "Revised down 4pp. Contrarian's point about tactical tariff bluffing has historical support. Updating base rate: if prior USTR page changes have been reversed, my recession probability should discount for that pathway.", key_evidence: ["Tactical bluffing documented historically", "Reducing base rate weight", "Revised 52%→48%"], round_number: 2 },
            { agent_name: "Contrarian", agent_role: "contrarian", probability: 0.28, confidence: 0.68, reasoning: "Maintaining. The market's cascade move happened BEFORE news broke — that's PREDATOR catching informed flow. But informed flow could be wrong too. Early buyers are often wrong in tariff scenarios (happened in 2018).", key_evidence: ["Informed flow preceded news = interesting", "But early tariff buyers wrong in 2018", "Maintaining 28%"], round_number: 2 },
            { agent_name: "Quant", agent_role: "quant", probability: 0.66, confidence: 0.77, reasoning: "Minor revision. The on-chain data is what it is — VPIN 0.81 with cascade score 0.87 is rare. That said, the Contrarian's 2025 precedents are worth a small discount. Yuan futures have NOT revised since my last check — still pricing 3.2% devaluation.", key_evidence: ["Yuan futures stable = conviction signal", "VPIN and cascade independent of news cycle", "Revised 69%→66%"], round_number: 2 },
          ],
        },
      ],
      judge_probability: 0.55,
      judge_confidence: 0.78,
      judge_reasoning: "Weighting Quant (independent cross-market evidence, VPIN/Yuan futures) and Bear (structural China dynamic) most heavily. Contrarian's 2025 precedents deserve respect but China tariffs have different political durability than allied-country threats. USTR gov page change is harder evidence than social media. Historian's base rate at 43-48% plus the RIPPLE structural analysis converges near 55%. Final: 55%.",
      dissenting_view: "Contrarian may be right — this could be a 60-day walkback trade. Trump negotiates with tariff threats. If this reverts before Monday, this trade loses the full $50. Risk is real.",
      offsetMs: 38000,
    },
  ],
  trades: [
    {
      market_id: "us-recession-2026",
      market_question: "Will US GDP contract for 2+ consecutive quarters in H2 2026?",
      direction: "YES",
      estimated_probability: 0.65,
      market_price: 0.22,
      edge: 0.43,
      kelly_fraction: 0.05,
      bet_amount: 50.0,
      confidence: 0.78,
      rationale: "Fused 4 signals. Raw: 0.545 → RIPPLE +0.08 → 0.590 → Extremized: 0.650. Edge: 43.0% (YES). Kelly capped at 5% = $50.00. Large edge, max-bet protection engaged.",
      timestamp: new Date().toISOString(),
      offsetMs: 96000,
    },
  ],
  rippleEvents: [
    { offsetMs: 26000, sourceNodeId: "Tariffs" },
    { offsetMs: 29000, sourceNodeId: "Trade War" },
    { offsetMs: 32000, sourceNodeId: "Supply Chain" },
    { offsetMs: 35000, sourceNodeId: "Inflation" },
    { offsetMs: 38000, sourceNodeId: "S&P 500" },
  ],
};
